### ISSUE TITLE
TODO's

### ISSUE THREAD

**Issue by dpollock** [ArkTaskMakers/MakerTracker#11]
Adding Auth0 into Angular/C# api
   - that will auto-inject the JWT on each api request

Re-create DB with new migrations

Setup CI/CD pipeline again

Typewriter extension
	- needs a template to follow

Create Views:
    Admin 
       - Manage Products *
       - Manage Equipment
       - View to see current product supply (ag-grid?)

    Maker 
      - Ensuring Profile is populated when they hit the site (name)
      - Ability to add "products" to their inventory

Notifications
   - Ability to send sms/email via sendgrid
   - add slack notifications on signups/updates from makers

**Comment by SonicZentropy** [comment]
Moved to individual issues
