### ISSUE TITLE
make a button on each page: "Problems? Questions? Comments?" Contact page

### ISSUE THREAD

**Issue by piercegordon1** [ArkTaskMakers/MakerTracker#62]
Let's have the link go to a Contact page that lets them enter: 

The link should record the page where the link was clicked on (dashboard vs. admin)

Their Name
Their Email
An option list: "Problems? Questions? Comments?"

For problems, an open dialogue box with the text below: 

"Please list the issue. You can describe what you did and what you expected, and what happened instead."

For questions: an open dialogue box with the text below:  

"What questions do you have?"

For Comments: an open dialogue box with the text below: 

"Let us know what's on your mind!"

**Comment by piercegordon1** [comment]
Also, I realized we needed another category: New product?

We should ask them to tell us: 

If you can make, or need, a product that isn't in the list, please put in your message: 
The exact product name,
A product description, including the designated audience, the materials, the 
A hyperlink showing an example of the product on the internet, 
and a picture of the product.

**Comment by piercegordon1** [comment]
Send them to pgordon@arhub.org

**Comment by mcaden** [comment]
I also added an admin screen that displays any feedback received.
