### ISSUE TITLE
Issues with the final 'Next' on the onborading screen

### ISSUE THREAD

**Issue by piercegordon1** [ArkTaskMakers/MakerTracker#63]
The issue happened twice: once was in the Equipment section above with an administrator, 
![5 20 2020](https://user-images.githubusercontent.com/11165717/83296278-1fed8100-a1b6-11ea-905c-bce848f1a149.png)

and in the final section, below, with a separate administrator. 
![5 20 2020 - 1](https://user-images.githubusercontent.com/11165717/83297122-9a6ad080-a1b7-11ea-99f2-e5e0a3af7f0e.png)

They had to click it more than once before it moved to the next category. It also did not show an error message, on the first instance.

**Comment by mcaden** [comment]
On the "supply" step - what was in the product section above it? (they are validated together)

For the last step, it's actually saving all the data to the database. I suspect it was simply working on it. We'll need to add a "busy" indicator and disable the button if it's still working on it.
