### ISSUE TITLE
Ensuring people who have logged in know their information is already there.

### ISSUE THREAD

**Issue by piercegordon1** [ArkTaskMakers/MakerTracker#65]
Obviously, a lot of makers have logged into the platform and put in their information. For those that use the same email, we should let them know that some of their information is in the system, but we're likely going to need more. 

For example: if they have their name and contact info, we could autopopulate that information into the onboarding screen, but leave space for the categories that have yet to be included.

(this could be tested by admins who test the onboarding screen, and can see their info autopopulated in the answer categories outlined as well, ready to be changed if needed, maybe like so:

![image](https://user-images.githubusercontent.com/11165717/83298120-7f995b80-a1b9-11ea-8940-59d77099a1e8.png)

**Comment by mcaden** [comment]
As I understand it we intend to import users. With that being the case, the onboarding will not display for them and they'll have stuff on their dashboard from the get-go. Is this acceptable?

**Comment by piercegordon1** [comment]
Well, the problem is we didn't originally ask for the products with the amount of granularity we previously required. So, people would use the onboarding screen to include that info. 

Also, I'd argue people need a bit more information to know what they should do once they've logged in, and the onboarding screen is a great alternative for that. Instead, the screen could possibly have 'optional' sections for people who've filled it out already, or something... honestly spitballing here. 

Would it be possible to display previous input information into the demographic input categories?

**Comment by mcaden** [comment]
We'll need to change a bit of current functionality but it's doable.

**Comment by piercegordon1** [comment]
if you haven't worked on this issue, let's talk through options on the platform during the meeting today.
