### ISSUE TITLE
No way to delete the products in the inventory

### ISSUE THREAD

**Issue by piercegordon1** [ArkTaskMakers/MakerTracker#70]
I'd say we need a 'delete' button on the dashboard as well, separate from the 'I now have zero' functionality when you make a delivery or add in your numbers...

And, this is an issue both for 'requestors' and 'suppliers.'

![image](https://user-images.githubusercontent.com/11165717/83304182-06533600-a1c4-11ea-9f5b-55096359be3b.png)

**Comment by mcaden** [comment]
If you edit the amount you have and change it to zero it will drop off.

**Comment by piercegordon1** [comment]
it didn't for me.... I see this

![image](https://user-images.githubusercontent.com/11165717/83306781-d8242500-a1c8-11ea-82fe-b9103ead66eb.png)

**Comment by mcaden** [comment]
Strange, will look into it

**Comment by mcaden** [comment]
This accidentally got associated to a PR and it closed, reopening.

**Comment by mcaden** [comment]
This was related to transactions `To` and `From` the same user.
