### ISSUE TITLE
Multiple Categories of Face Shields? No, ONE category. (onboarding)

### ISSUE THREAD

**Issue by piercegordon1** [ArkTaskMakers/MakerTracker#73]
When we tried to add the ability to make certain number of face shields and masks as suppliers, no matter the number of categories, it only counted the registrations as a single product category ( I believe, the Prusa Faceshield). 

None of the other categories showed up in the 'supplier' section on the Dashboard. Though I'm not sure, I believe it only showed up as a Prusa Face shield number. Each of these categories should have their own numbers, both as inputs on the onboarding screen, and visible numbers and inputs on the Dashboard.
![image](https://user-images.githubusercontent.com/11165717/83435775-6afbd400-a402-11ea-9354-485524a1cb2a.png)

**Comment by mcaden** [comment]
This is related to a bug that was fixed. Adding a product threw an error and stopped adding products to the UI. This was also the reason the "Next" button wasn't working.
